---
site_name: "LTRCCT-2001: Demystifying Multilingual Omnichannel Experiences with Webex Contact Center AI" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
site_description: "LTRCCT-2001: Demystifying Multilingual Omnichannel Experiences with Webex Contact Center AI" # must be same as "site_name"
site_author: Carolina Morales
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.collapse
    - search.suggest
    - content.code.copy
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/WebexCC-SA/multilingual_CCAI.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/Wx1_25_PDF_image.jpg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav: 
  - Overview:
        - Learining Objectives: overview.md
  - Activities:
      - Getting Started: getting_started.md
      - Lab 1 - Multilingual Voice AI: voice.md
      - Lab 2 - Digital Patient Journey: digital.md
      - Lab 3 - Intelligent AI Assistant: AI_Assistant.md 
      - Lab 4 - Bonus - Analytics: bonus.md
  - Wrap up: wrap.md
  
 